enum Genre: String, CaseIterable {
    case pop = "Pop"
    case jpop = "J-Pop"
    case rock = "Rock"
    case hipHop = "Hip-Hop"
    case rap = "Rap"
    case archievecore = "Arhievecore"
    case trap = "Trap"
    case rnb = "R&B"
    case electronic = "Electronic"
    case house = "House"
    case techno = "Techno"
    case jazz = "Jazz"
    case blues = "Blues"
    case classical = "Classical"
    case metal = "Metal"
    case punk = "Punk"
    case indie = "Indie"
    case folk = "Folk"
    case country = "Country"
    case reggae = "Reggae"
    case soul = "Soul"
    case funk = "Funk"
    case other = "Other"
}
